### ISSUE TITLE
An actual gateway interface example : maybe will insipre us

### ISSUE THREAD

**Issue by gil-obradors** [estevebadia/odoo-community-currency#3]
https://github.com/odoo/odoo/tree/master/addons/pos_mercury

**Comment by estevebadia** [comment]
Yes, It will be very useful to take a look! If I'm right, this is an addon for a credit card reader, so I suppose that "mercury" appears as an additional payment method in PoS, and when it is selected, it sends the data (the cost) to the card reader. Then the card reader asynchronously makes de payment and, if successful, it registers the payment back to the relevant journal in odoo.

Our gateway client would be similar architecture, but we need to identify and send the community currency account of the customer to the gateway addon in addition to the amount to be paid.

Yes, definitely may be a good source of inspiration! Thanks!

**Comment by estevebadia** [comment]
I've been studying a bit the `pos_mercury` addon. Indeed very informative. Just for later record, I write here what I've seen:

Backend:
- Create a model `PosMercuryConfiguration` with the merchand payment credentials.
- Add a new field in `pos.payment.method` model so it can have a pointer to PosMercuryConfiguration
- Add fields (card number, etc) in `pos.payment` model
- Extend the function `_payment_fields` in `pos.order` so that it returns the new fields defined in `pos.payment`.
- Create a new model `PosMercuryTransaction` with some functions that call the mercury API.

FrontEnd:
 - Extend `pos_model.Paymentline` so it correcly imports and exports the new fields to JSON.
 - Augment `PaymentScreenWidget` (the payment screen) so that when UI actions are triggered (such as cancel payment or swiping the card) it makes a payment call (through the functions defined in `PosMercuryTransaction`) and updates the `pos_model.Paymentline` object in the order accordingly.

PS: This page shows the view of the new objects in the backend: https://www.odoo.com/documentation/user/12.0/point_of_sale/advanced/mercury.html

I could definitely try to create a prototype based on this architecture; I'll do it when I find the time!

**Comment by gil-obradors** [comment]
Good news!
I'm working hard with JS this days, so I think we achieve it yes or yes!

The point that I don't know now is How the customer will pass his credentials to the shop assistant.
And how the customer writte a... pin? :rofl:

**Comment by estevebadia** [comment]
For our particular use case (integration with IntegralCES platform) we don't need any customer credentials or pin. The community currency (cc) account number will be previously set in the customer profile. In the moment of the sale, the PoS makes an API call using the customer account number and the merchand credentials. This payment will either become automatically accepted or pending, depending on the customer cc account configuration. We may ask all SuperCoop customers to whitelist the SuperCoop account so all charges from SuperCoop are automatically accepted, or even to allow all incomming payments. These are available features in the cc platform integralces.net. Note that, differently from the conventional transactions, cc transactions in integralces are ususally charges not payments; that works in our favor.

In case customer doesn't have the correct configuration and the payment is in pending state, we may ask the customer to accept the payment in the moment, using their smartphone, and poll the updated transaction state from the PoS. Otherwise I think the best at this moment is to just cancel the payment and ask the customer to pay using an alternative or allow charges from the merchand account.

**Comment by gil-obradors** [comment]
Maybe other source:

https://github.com/OCA/l10n-spain/tree/12.0/payment_redsys
But I haven't read all yet

**Comment by estevebadia** [comment]
This is an Odoo Payment Acquirer: payment gateway for the ecommerce page
and quotations send by email. So out of our immediate roadmap I think. But
worth knowing anyway

El dg., 26 abr. 2020, 9.38, Gil Obradors <notifications@github.com> va
escriure:

**Comment by estevebadia** [comment]
I've created the module based on pos_mercury :) Comments welcomed!

https://github.com/estevebadia/odoo-community-currency/pull/4

**Comment by estevebadia** [comment]
Continue the discussion in PR https://github.com/estevebadia/odoo-community-currency/pull/4
